### ISSUE TITLE
question about the runtimeerror

### ISSUE THREAD

**Issue by xinli2008** [wyu97/Easy-use-BART#2]
Hello, thank you for sharing nice job~ i want to reprdocue this project and then run the permGen project.
But when i run CUDA_VISIBLE_DEVICES=0 bash scripts/train_rocstory.sh, it always reminds:
RuntimeError: CUDA out of memory. Tried to allocate 982.00 MiB (GPU 0; 10.76 GiB total capacity; 7.80 GiB already allocated; 603.44 MiB free; 9.16 GiB reserved in total by PyTorch)
Prehaps it is the problem of batch_size, and i modify the line 363 in seq2seq_trainer.py with:
logger.info("  Total train batch size (w. parallel, distributed & accumulation) = %d", 64)
and per_device_train_batch_size=16 ,per_device_eval_batch_size=8  in train_rocstory.sh
It finally works, and i want to know Is there any other better way to modify the RunTimeError?

**Comment by xinli2008** [comment]
sorry to bother you again! I notice that you utilize RAKE to extract keywords in the text.
can you share with the code? because i want to make a comparision with [keybert](https://github.com/MaartenGr/KeyBERT) on my text dataset
Thank you 
best

**Comment by wyu97** [comment]
Hi, 

The out of memory issue is caused by too large batch size. I tested the code on 32GB V100s. If you are using a 11GB GPU to run the code, I suggest you use 4 as batch size and use gradient accumulation "--gradient_accumulation 16". It means you update the parameters after 16 times forward, which equals to using 4*16=64 as batch size. 

Also, for RAKE, I directly use https://github.com/zelandiya/RAKE-tutorial without any modification. Please let me know if you have any other questions and I am happy to help them. 

Best,
Wenhao

**Comment by xinli2008** [comment]
Thank you for your kind help~ Have a nice day -)
